[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/python"
include_regex = "2\\.\\d+\\.?\\d+-alpine\\d\\.\\d+"

[FFSYNC]
source = "github"
github = "mozilla-services/syncserver"
use_max_tag = true
